import { Component } from '@angular/core';
import { NzFormatEmitEvent, NzTreeNode } from 'ng-zorro-antd';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less'],
  host: {
    '[style.width]': "'100%'",
    '[style.height]': "'100%'"
  }
})
export class AppComponent {
  title = 'TMS';
  menuVal = 'TMS';
  value = '';
  activedNode: NzTreeNode;
  imageArray = [1,2,3,4];
  checked = true;
  listOfData = [
    {
      key: '1',
      name: 'John Brown',
      type: 'xxxxxxxxxx',
      desc: 'xxxxxxxxxx',
      mname: 'New York',
    },
    {
      key: '2',
      name: 'Jim Green',
      type: 'xxxxxxxxxx',
      desc: 'xxxxxxxxxx',
      mname: 'London',
    },
    {
      key: '3',
      name: 'Joe Black',
      type: 'xxxxxxxxxx',
      desc: 'xxxxxxxxxx',
      mname: 'Sidney',
    },
    {
      key: '4',
      name: 'Jim Red',
      age: 18,
      type: 'xxxxxxxxxx',
      desc: 'xxxxxxxxxx',
      mname: 'Washington',
    },
    {
      key: '5',
      name: 'Jake White',
      type: 'xxxxxxxxxx',
      desc: 'xxxxxxxxxx',
      mname: 'Dublin',
    }
  ];

  nodes = [{
    title: 'Group 1',
    key: '1001',
    expanded: true,
    children: [
      { title: 'beam1', key: '10010', isLeaf: true },
      { title: 'beam2', key: '10011', isLeaf: true },
      { title: 'beam3', key: '10012', isLeaf: true },
      { title: 'beam4', key: '10013', isLeaf: true },
      { title: 'beam5', key: '10014', isLeaf: true }
    ]
  }, {
    title: 'Group 2',
    key: '1002',
    expanded: true,
    children: [
      { title: 'beam1', key: '10020', isLeaf: true },
      { title: 'beam2', key: '10021', isLeaf: true },
      { title: 'beam3', key: '10022', isLeaf: true },
      { title: 'beam4', key: '10023', isLeaf: true },
      { title: 'beam5', key: '10024', isLeaf: true }
    ]
  }, {
    title: 'Group 3',
    key: '1003',
    children: [
      { title: 'beam1', key: '10030', isLeaf: true },
      { title: 'beam2', key: '10031', isLeaf: true },
      { title: 'beam3', key: '10032', isLeaf: true },
      { title: 'beam4', key: '10033', isLeaf: true },
      { title: 'beam5', key: '10034', isLeaf: true }
    ]
  }];
  dateList = [
    {
      key: 1,
      name: '',
      list: [
        {value: 'M'},
        {value: 'T'},
        {value: 'W'},
        {value: 'TH'},
        {value: 'F'},
        {value: 'SAT'},
        {value: 'S'},
        {value: 'M'},
        {value: 'T'},
        {value: 'W'},
        {value: 'TH'},
        {value: 'F'},
        {value: 'SAT'},
        {value: 'S'},
        {value: 'M'},
        {value: 'T'},
        {value: 'W'},
        {value: 'TH'},
        {value: 'F'},
        {value: 'SAT'},
        {value: 'S'},
        {value: 'M'},
        {value: 'T'},
        {value: 'W'},
        {value: 'TH'},
        {value: 'F'},
        {value: 'SAT'},
        {value: 'S'},
        {value: 'M'},
        {value: 'T'},
        {value: 'W'},
        {value: 'TH'},
        {value: 'F'},
        {value: 'SAT'},
        {value: 'S'},
        {value: 'M'},
        {value: 'T'},
        {value: 'W'},
        {value: 'TH'},
        {value: 'F'},
        {value: 'SAT'},
        {value: 'S'},
        {value: 'M'},
        {value: 'T'},
        {value: 'W'},
        {value: 'TH'},
        {value: 'F'},
        {value: 'SAT'},
        {value: 'S'},
        {value: 'M'},
        {value: 'T'},
        {value: 'W'},
        {value: 'TH'},
      ],
    },
    
    {
      key: 2,
      name: 'Date',
      list: [
        {value: '2018 JUL',t: 1},
        {value: '17'},
        {value: '18'},
        {value: '19'},
        {value: '20'},
        {value: '21'},
        {value: '22'},
        {value: '23'},
        {value: '24'},
        {value: '25'},
        {value: '26'},
        {value: '27'},
        {value: '28'},
        {value: '29'},
        {value: '30'},
        {value: '31'},
        {value: '2018 AUG',t: 1},
        {value: '2'},
        {value: '3'},
        {value: '4'},
        {value: '5'},
        {value: '6'},
        {value: '7'},
        {value: '8'},
        {value: '9'},
        {value: '10'},
        {value: '11'},
        {value: '12'},
        {value: '13'},
        {value: '14'},
        {value: '15'},
        {value: '16'},
        {value: '17'},
        {value: '18'},
        {value: '19'},
        {value: '20'},
        {value: '21'},
        {value: '22'},
        {value: '23'},
        {value: '24'},
        {value: '25'},
        {value: '26'},
        {value: '27'},
        {value: '28'},
        {value: '29'},
        {value: '30'},
        {value: '31'},
        {value: '2019 Leb'},
        {value: '2'},
        {value: '3'},
        {value: '4'},
        {value: '5'},
        {value: '6'},
      ],
    },
  ]

  listOfMapData = [
    {
      key: 3,
      name: 'Beam Group 1',
      list: [
        {value: '1', status: 1,count:'3/30 Fxs',info: '* Has been treated Fraction is unable to schedule again',msgType: 'Error Message'},
        {value: '2', status: 1},
        {value: '3', status: 1},
        {value: '4', status: 1},
        {value: '5', status: 1},
        {value: '6', status: 1},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '7', status: 1},
        {value: '8', status: 1},
        {value: '9', status: 1},
        {value: '10', status: 1},
        {value: '11', status: 1},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '12', status: 1},
        {value: '13', status: 3},
        {value: '14', status: 3},
        {value: '15', status: 1},
        {value: '16', status: 1},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '17', status: 1},
        {value: '18', status: 4},
        {value: '19', status: 4},
        {value: '20', status: 1},
        {value: '21', status: 1},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '22', status: 1},
        {value: '23', status: 1},
        {value: '24', status: 1},
        {value: '25', status: 1},
        {value: '26', status: 1},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '27', status: 1},
        {value: '28', status: 2},
        {value: '29', status: 2},
        {value: '30', status: 2},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
      ],
      children: [
        {
          key: 11,
          name: 'Beam 1',
          list: [
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
          ],
        },
        {
          key: 12,
          name: 'Beam 2',
          list: [
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
          ]
        },
        {
          key: 13,
          name: 'Beam 3',
          list: [
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
          ]
        },
        {
          key: 24,
          name: 'Beam 4',
          list: [
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
          ],
        }
      ]
    },
    {
      key: 4,
      name: 'Beam Group 2',
      list: [
        {value: '1', status: 1},
        {value: '2', status: 1},
        {value: '3', status: 1},
        {value: '4', status: 3},
        {value: '5', status: 4},
        {value: '6', status: 1},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '7', status: 1},
        {value: '8', status: 1},
        {value: '9', status: 1},
        {value: '10', status: 3},
        {value: '11', status: 1},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '12', status: 1},
        {value: '13', status: 1},
        {value: '14', status: 1},
        {value: '15', status: 1},
        {value: '16', status: 1},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '17', status: 1},
        {value: '18', status: 1},
        {value: '19', status: 1},
        {value: '20', status: 4},
        {value: '21', status: 1},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '22', status: 1},
        {value: '23', status: 1},
        {value: '24', status: 1},
        {value: '25', status: 1},
        {value: '26', status: 1},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '27', status: 1},
        {value: '28', status: 2},
        {value: '29', status: 2},
        {value: '30', status: 2},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
        {value: '', status: 0},
      ],
      children: [
        {
          key: 22,
          name: 'Beam 2',
          list: [
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
          ],
        },
        {
          key: 26,
          name: 'Beam 6',
          list: [
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
          ],
        },
        {
          key: 22,
          name: 'Beam 2',
          list: [
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 3},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 4},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
          ],
        },
        {
          key: 23,
          name: 'Beam 3',
          list: [
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
          ],
        },
        {
          key: 24,
          name: 'Beam 4',
          list: [
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 1},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 1},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 2},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
            {value: '', status: 0},
          ],
        }
      ]
    }
  ];

  activeNode(data: NzFormatEmitEvent): void {
    this.activedNode = data.node;
  }

  pre(data: string): void {
    console.log(1111,data)
  }

  handleValue(data: string): String {
    // console.log(1111,data)
    var temp = data
    if(data) {
      temp = data
    }else {
      temp = '  '
    }
    return temp
  }

  log(data: string): void {
    this.menuVal = data;
    // console.log(data);
  }
  mapOfExpandedData: { [key: string]: TreeNodeInterface[] } = {};

  collapse(array: TreeNodeInterface[], data: TreeNodeInterface, $event: boolean): void {
    if ($event === false) {
      if (data.children) {
        data.children.forEach(d => {
          const target = array.find(a => a.key === d.key)!;
          target.expand = false;
          this.collapse(array, target, false);
        });
      } else {
        return;
      }
    }
  }

  convertTreeToList(root: object): TreeNodeInterface[] {
    const stack: any[] = [];
    const array: any[] = [];
    const hashMap = {};
    stack.push({ ...root, level: 0, expand: false });

    while (stack.length !== 0) {
      const node = stack.pop();
      this.visitNode(node, hashMap, array);
      if (node.children) {
        for (let i = node.children.length - 1; i >= 0; i--) {
          stack.push({ ...node.children[i], level: node.level + 1, expand: false, parent: node });
        }
      }
    }

    return array;
  }

  visitNode(node: TreeNodeInterface, hashMap: { [key: string]: any }, array: TreeNodeInterface[]): void {
    if (!hashMap[node.key]) {
      hashMap[node.key] = true;
      array.push(node);
    }
  }


  ngOnInit(): void {
    this.listOfMapData.forEach(item => {
      this.mapOfExpandedData[item.key] = this.convertTreeToList(item);
    });
  }
}

export interface TreeNodeInterface {
  key: number;
  name: string;
  age: number;
  level: number;
  expand: boolean;
  address: string;
  children?: TreeNodeInterface[];
}
